# Generated by Django 3.0.7 on 2020-07-13 08:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254, unique=True)),
                ('author_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Use the format: +(country) eg +2347000000123', max_length=128, null=True, region=None)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Author'),
        ),
    ]
